### ISSUE TITLE
403 Error from getWork()

### ISSUE THREAD

**Issue by leonidez** [vsivsi/meteor-job#11]
I receive this error randomly when a long-running worker goes to fetch more work:

```
Received error from getWork():  { error: 403,
  reason: 'Method not authorized',
  details: 'Authenticated user is not permitted to invoke this method.',
  message: 'Method not authorized [403]',
  errorType: 'Meteor.Error' }
```

At first I thought this was related to the worker using a high volume of memory, but after refactoring to reduce memory pressure the problem persists, though not as often. Each worker runs in a separate node process and is definitely authenticated well before the error occurs (a worker will easily have processed several dozen jobs before erroring out).

The ddp login methods are wrapped using Bluebird. Here is the setup:

```
const { ddp } = require('../helpers/ddp');
const ddpLogin = require('ddp-login');
const { promisifyAll } = require('bluebird');

const { JOB_USER, JOB_PASS } = process.env;

const ddpPromised = promisifyAll(ddp);
const ddpLoginPromised = promisifyAll(ddpLogin);

exports.ddpConnectAsync = (userName = JOB_USER, password = JOB_PASS) => {
  return ddpPromised.connectAsync().then(() => {
    return ddpLoginPromised.loginWithUsernameAsync(ddp, userName, password);
  });
};
```

The `ddp` object is of this form:

```
exports.ddp = new DDP({
  host: PROD_HOST,
  port: parseInt(PROD_DDP_PORT, 10),
  use_ejson: true,
  autoReconnect: true,
  autoReconectTimer: 1000,
});
```

With an eye to testing we have created a small class wrapper around the Jobs collection.

```
const Job = require('meteor-job');
const _ = require('lodash');
const { ddp } = require('../helpers/ddp');

exports.Worker = class Worker {
  constructor(jobName, jobHandleFunction) {
    const isValid = (jobName && _.isString(jobName)) &&
                    (jobHandleFunction && _.isFunction(jobHandleFunction));

    if (isValid) {
      this._setup(jobName, jobHandleFunction);
    } else {
      this._throwError('Worker requires a jobName and jobHandleFunction');
    }
  }

  _setup(jobName, jobHandleFunction) {
    this.jobName = jobName;
    this.jobHandleFunction = jobHandleFunction;
  }

  _throwError(desc) {
    throw new Error(desc);
  }

  init() {
    // resets the ddp connection to prevent mocha watch throwing errors
    Job._ddp_apply = undefined;
    Job.setDDP(ddp);
    console.log(`${this.jobName} is waiting...`);
    this.queue = Job.processJobs('jobs', this.jobName, this.jobHandleFunction);
  }
};
```

And this is how we init the worker:

```
const { ddpConnectAsync } = require('../helpers/ddp-connect');
const { Worker } = require('../helpers/Worker');
const { handleExport } = require('./exporter/handle-export');

ddpConnectAsync().then(() => {
  const foreman = new Worker('Exporter.Foreman', handleExport);
  foreman.init();
});
```

Thanks for any help you can provide.

**Comment by vsivsi** [comment]
Hi, whatever is happening here seems likely to be happening on the server-side, and not the worker/client. That is, unless the worker is somehow losing its authentication credentials, which would either be an app or DDP connection issue, but you say that the worker **is** authenticated, so...

This issue should probably be refiled over there:  https://github.com/vsivsi/meteor-job-collection/issues

To help, I really need to have access to a minimal running reproduction of the issue with clear instructions on how to reproduce. I'm sure you appreciate the difficulty of debugging intermittent problems even _with_ the running code in front of you. In my experience, remotely trying to debug something like this without access to a full reproduction is not an efficient use of anyone's time.

At a very minimum, you should turn-on server-side logging so you can see all of the method calls leading up to the error have reported here:  https://github.com/vsivsi/meteor-job-collection#logging

**Comment by leonidez** [comment]
Thanks for your feedback. We ended up removing the bluebird promise wrappers and used the callback style ddp and ddp-login functions. Haven't seen the issue since.

**Comment by vsivsi** [comment]
Okay, thanks for letting me know.
